//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voyage_Guide_Client.VoyageClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRegister", Namespace="http://schemas.datacontract.org/2004/07/Voyage_Guide.Models")]
    [System.SerializableAttribute()]
    public partial class UserRegister : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Custom_Exception", Namespace="http://schemas.datacontract.org/2004/07/Voyage_Guide.Models")]
    [System.SerializableAttribute()]
    public partial class Custom_Exception : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoyageData", Namespace="http://schemas.datacontract.org/2004/07/Voyage_Guide.Models")]
    [System.SerializableAttribute()]
    public partial class VoyageData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoyageCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoyageContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoyageStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imageDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoyageCity {
            get {
                return this.VoyageCityField;
            }
            set {
                if ((object.ReferenceEquals(this.VoyageCityField, value) != true)) {
                    this.VoyageCityField = value;
                    this.RaisePropertyChanged("VoyageCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoyageContent {
            get {
                return this.VoyageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.VoyageContentField, value) != true)) {
                    this.VoyageContentField = value;
                    this.RaisePropertyChanged("VoyageContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoyageState {
            get {
                return this.VoyageStateField;
            }
            set {
                if ((object.ReferenceEquals(this.VoyageStateField, value) != true)) {
                    this.VoyageStateField = value;
                    this.RaisePropertyChanged("VoyageState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imageData {
            get {
                return this.imageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.imageDataField, value) != true)) {
                    this.imageDataField = value;
                    this.RaisePropertyChanged("imageData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoyageClient.IRegisterService")]
    public interface IRegisterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/registerUser", ReplyAction="http://tempuri.org/IRegisterService/registerUserResponse")]
        bool registerUser(Voyage_Guide_Client.VoyageClient.UserRegister user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/registerUser", ReplyAction="http://tempuri.org/IRegisterService/registerUserResponse")]
        System.Threading.Tasks.Task<bool> registerUserAsync(Voyage_Guide_Client.VoyageClient.UserRegister user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterServiceChannel : Voyage_Guide_Client.VoyageClient.IRegisterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterServiceClient : System.ServiceModel.ClientBase<Voyage_Guide_Client.VoyageClient.IRegisterService>, Voyage_Guide_Client.VoyageClient.IRegisterService {
        
        public RegisterServiceClient() {
        }
        
        public RegisterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool registerUser(Voyage_Guide_Client.VoyageClient.UserRegister user) {
            return base.Channel.registerUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> registerUserAsync(Voyage_Guide_Client.VoyageClient.UserRegister user) {
            return base.Channel.registerUserAsync(user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoyageClient.IAuthService")]
    public interface IAuthService {
        
        // CODEGEN: Generating message contract since the wrapper name (AuthenticateUser) of message AuthenticateUser does not match the default value (authenticateUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/authenticateUser", ReplyAction="http://tempuri.org/IAuthService/authenticateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Voyage_Guide_Client.VoyageClient.Custom_Exception), Action="http://tempuri.org/IAuthService/authenticateUserCustom_ExceptionFault", Name="Custom_Exception", Namespace="http://schemas.datacontract.org/2004/07/Voyage_Guide.Models")]
        Voyage_Guide_Client.VoyageClient.AuthenticateReply authenticateUser(Voyage_Guide_Client.VoyageClient.AuthenticateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/authenticateUser", ReplyAction="http://tempuri.org/IAuthService/authenticateUserResponse")]
        System.Threading.Tasks.Task<Voyage_Guide_Client.VoyageClient.AuthenticateReply> authenticateUserAsync(Voyage_Guide_Client.VoyageClient.AuthenticateUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUser {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string VoyagePassword;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string VoyageUserName;
        
        public AuthenticateUser() {
        }
        
        public AuthenticateUser(string VoyagePassword, string VoyageUserName) {
            this.VoyagePassword = VoyagePassword;
            this.VoyageUserName = VoyageUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateReply", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateReply {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int VoyageUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool VoyageisAuthenticated;
        
        public AuthenticateReply() {
        }
        
        public AuthenticateReply(int VoyageUserId, bool VoyageisAuthenticated) {
            this.VoyageUserId = VoyageUserId;
            this.VoyageisAuthenticated = VoyageisAuthenticated;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : Voyage_Guide_Client.VoyageClient.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<Voyage_Guide_Client.VoyageClient.IAuthService>, Voyage_Guide_Client.VoyageClient.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Voyage_Guide_Client.VoyageClient.AuthenticateReply Voyage_Guide_Client.VoyageClient.IAuthService.authenticateUser(Voyage_Guide_Client.VoyageClient.AuthenticateUser request) {
            return base.Channel.authenticateUser(request);
        }
        
        public int authenticateUser(string VoyagePassword, string VoyageUserName, out bool VoyageisAuthenticated) {
            Voyage_Guide_Client.VoyageClient.AuthenticateUser inValue = new Voyage_Guide_Client.VoyageClient.AuthenticateUser();
            inValue.VoyagePassword = VoyagePassword;
            inValue.VoyageUserName = VoyageUserName;
            Voyage_Guide_Client.VoyageClient.AuthenticateReply retVal = ((Voyage_Guide_Client.VoyageClient.IAuthService)(this)).authenticateUser(inValue);
            VoyageisAuthenticated = retVal.VoyageisAuthenticated;
            return retVal.VoyageUserId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Voyage_Guide_Client.VoyageClient.AuthenticateReply> Voyage_Guide_Client.VoyageClient.IAuthService.authenticateUserAsync(Voyage_Guide_Client.VoyageClient.AuthenticateUser request) {
            return base.Channel.authenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Voyage_Guide_Client.VoyageClient.AuthenticateReply> authenticateUserAsync(string VoyagePassword, string VoyageUserName) {
            Voyage_Guide_Client.VoyageClient.AuthenticateUser inValue = new Voyage_Guide_Client.VoyageClient.AuthenticateUser();
            inValue.VoyagePassword = VoyagePassword;
            inValue.VoyageUserName = VoyageUserName;
            return ((Voyage_Guide_Client.VoyageClient.IAuthService)(this)).authenticateUserAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoyageClient.IVoyageDataSerrvice")]
    public interface IVoyageDataSerrvice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/addNewData", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/addNewDataResponse")]
        bool addNewData(Voyage_Guide_Client.VoyageClient.VoyageData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/addNewData", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/addNewDataResponse")]
        System.Threading.Tasks.Task<bool> addNewDataAsync(Voyage_Guide_Client.VoyageClient.VoyageData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/getImage", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/getImageResponse")]
        byte[] getImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/getImage", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/getImageResponse")]
        System.Threading.Tasks.Task<byte[]> getImageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/addNewVoyageData", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/addNewVoyageDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Voyage_Guide_Client.VoyageClient.Custom_Exception), Action="http://tempuri.org/IVoyageDataSerrvice/addNewVoyageDataCustom_ExceptionFault", Name="Custom_Exception", Namespace="http://schemas.datacontract.org/2004/07/Voyage_Guide.Models")]
        bool addNewVoyageData(Voyage_Guide_Client.VoyageClient.VoyageData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoyageDataSerrvice/addNewVoyageData", ReplyAction="http://tempuri.org/IVoyageDataSerrvice/addNewVoyageDataResponse")]
        System.Threading.Tasks.Task<bool> addNewVoyageDataAsync(Voyage_Guide_Client.VoyageClient.VoyageData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoyageDataSerrviceChannel : Voyage_Guide_Client.VoyageClient.IVoyageDataSerrvice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoyageDataSerrviceClient : System.ServiceModel.ClientBase<Voyage_Guide_Client.VoyageClient.IVoyageDataSerrvice>, Voyage_Guide_Client.VoyageClient.IVoyageDataSerrvice {
        
        public VoyageDataSerrviceClient() {
        }
        
        public VoyageDataSerrviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoyageDataSerrviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyageDataSerrviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyageDataSerrviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addNewData(Voyage_Guide_Client.VoyageClient.VoyageData data) {
            return base.Channel.addNewData(data);
        }
        
        public System.Threading.Tasks.Task<bool> addNewDataAsync(Voyage_Guide_Client.VoyageClient.VoyageData data) {
            return base.Channel.addNewDataAsync(data);
        }
        
        public byte[] getImage() {
            return base.Channel.getImage();
        }
        
        public System.Threading.Tasks.Task<byte[]> getImageAsync() {
            return base.Channel.getImageAsync();
        }
        
        public bool addNewVoyageData(Voyage_Guide_Client.VoyageClient.VoyageData data) {
            return base.Channel.addNewVoyageData(data);
        }
        
        public System.Threading.Tasks.Task<bool> addNewVoyageDataAsync(Voyage_Guide_Client.VoyageClient.VoyageData data) {
            return base.Channel.addNewVoyageDataAsync(data);
        }
    }
}
